import fs from"node:fs";
import assert from"node:assert/strict";
const b="apps/android/app/src/main";
const voice=fs.readFileSync(b+"/java/industries/leeway/devicebridge/VoiceRuntime.kt","utf8");
const router=fs.readFileSync(b+"/java/industries/leeway/devicebridge/RemoteCommandRouter.kt","utf8");
const activity=fs.readFileSync(b+"/java/industries/leeway/devicebridge/MainActivity.kt","utf8");
const manifest=fs.readFileSync(b+"/AndroidManifest.xml","utf8");
const gradle=fs.readFileSync("apps/android/app/build.gradle.kts","utf8");

assert.doesNotMatch(voice,/TextToSpeech/);
assert.match(voice,/LEEWAY_VOICE_FABRIC/);
assert.match(voice,/agent-lee-voice-one/);
assert.match(voice,/fallbackAllowed/);
assert.match(voice,/VOICE_UNAVAILABLE/);
assert.match(voice,/openVoiceFabric/);
assert.match(router,/"voice\.speak"/);
assert.match(router,/"agent\.chat"/);
assert.match(router,/VoiceRuntime\.speak/);
assert.match(activity,/OPEN AGENT LEE VOICE ONE/);
assert.match(activity,/VoiceRuntime\.openVoiceFabric/);
assert.match(manifest,/RECORD_AUDIO/);
assert.match(manifest,/VoiceOneActivity/);
assert.match(voice,/android-bridge\.html/);
assert.match(gradle,/versionName = "0\.8\.6"/);
assert.match(gradle,/versionCode = 14/);
console.log("PASS Android Agent Lee Voice Fabric authority contract");
