import fs from"node:fs";
import assert from"node:assert/strict";
const b="apps/android/app/src/main";
const voice=fs.readFileSync(b+"/java/industries/leeway/devicebridge/VoiceRuntime.kt","utf8");
const router=fs.readFileSync(b+"/java/industries/leeway/devicebridge/RemoteCommandRouter.kt","utf8");
const activity=fs.readFileSync(b+"/java/industries/leeway/devicebridge/MainActivity.kt","utf8");
const manifest=fs.readFileSync(b+"/AndroidManifest.xml","utf8");
const gradle=fs.readFileSync("apps/android/app/build.gradle.kts","utf8");

assert.doesNotMatch(voice,/TextToSpeech/);
assert.match(voice,/LEEWAY_VOICE_FABRIC/);
assert.match(voice,/agent-lee-voice-one/);
assert.match(voice,/fallbackAllowed/);
assert.match(voice,/PLAYBACK_READY_SYNTHESIS_BODY_ROUTED/);
assert.match(voice,/VOICE_SYNTHESIS_REQUIRES_BODY_ROUTER/);
assert.match(voice,/ANDROID_NATIVE_MEDIA_PLAYER/);
assert.match(voice,/VOICE_ARTIFACT_HASH_MISMATCH/);
assert.match(voice,/fallbackAllowed", false|fallbackAllowed",false/);
assert.match(voice,/openVoiceFabric/);
assert.match(router,/"voice\.speak"/);
assert.match(router,/"voice\.play-artifact"/);
assert.match(router,/"voice\.stop"/);
assert.match(router,/"agent\.chat"/);
assert.match(router,/VoiceRuntime\.speak/);
assert.match(activity,/OPEN AGENT LEE VOICE ONE/);
assert.match(activity,/VoiceRuntime\.openVoiceFabric/);
assert.match(manifest,/RECORD_AUDIO/);
assert.match(gradle,/versionName = "0\.9\.10-c3-4"/);
console.log("PASS Android Agent Lee Voice Fabric authority contract");
