import fs from "node:fs";
import assert from "node:assert/strict";
const script=fs.readFileSync("clients/remote-controller/termux-one-pull.sh","utf8");
assert.match(script,/Waiting for Android update confirmation/);
assert.doesNotMatch(script,/Waiting for Android uninstall confirmation/);
assert.match(script,/Automatic uninstall is forbidden/);
assert.match(script,/\[LeeWay\]\[RUNNING\]/);
assert.match(script,/setInterval/);
assert.match(script,/TERMUX_BOOTSTRAP/);
assert.match(script,/owner-bootstrap\?nonce=/);
assert.doesNotMatch(script,/Pairing token:/);
console.log("PASS one-pull visible progress and state-preservation contract");
