#!/data/data/com.termux/files/usr/bin/bash
# LEEWAY HEADER — DO NOT REMOVE
# REGION: DEVICE.PHONE.QUALIFICATION
# TAG: DEVICE.LEEWAY.TERMUX.QUALIFY
# WHAT = Phone-local + remote Device Bridge qualification from Termux
# WHY = Prove the Fold execution path without requiring the PC or exposing the owner token to chat
# WHO = LeeWay Industries / Agent Lee / Creator
# WHERE = Galaxy Fold Termux -> Device Bridge loopback + production relay
# HOW = Local health pre-gate, hidden token prompt, canonical remote controller, evidence bundle
set -euo pipefail

DEVICE_ID="${LEEWAY_DEVICE_ID:-f30a80a743592e7d9cbe4b3113ef896db30bd80434df0afcb8591c04dbb84861}"
RELAY_URL="${LEEWAY_RELAY_URL:-wss://agent-lee-x.vercel.app/api/device-relay}"
PINNED_SHA="81703f27bf6968909ef844863518bde73cde5323"
BASE_RAW="https://raw.githubusercontent.com/4citeB4U/LEEWAY-DEVICE-BRIDGE/${PINNED_SHA}"
WORK_ROOT="${HOME}/.leeway/device-bridge-controller"
STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
EVIDENCE_DIR="${HOME}/leeway-evidence/device-bridge-${STAMP}"

say(){ printf '\n[LeeWay] %s\n' "$*"; }
fail(){ printf '\n[LeeWay][FAIL] %s\n' "$*" >&2; exit 1; }

say "Termux direct-phone qualification starting."
say "No pairing token will be printed or written to the evidence files."

command -v curl >/dev/null 2>&1 || { say "Installing curl"; pkg install -y curl; }
command -v node >/dev/null 2>&1 || { say "Installing Node.js"; pkg install -y nodejs; }
command -v npm >/dev/null 2>&1 || fail "npm is unavailable after Node.js installation."

mkdir -p "$WORK_ROOT" "$EVIDENCE_DIR"

say "GATE 1 — checking phone-local Device Bridge loopback at 127.0.0.1:5323."
LOCAL_HEALTH="$(curl -fsS --max-time 5 http://127.0.0.1:5323/health 2>/dev/null || true)"
if [ -z "$LOCAL_HEALTH" ]; then
  cat <<'TXT'
[LeeWay][BLOCKED] The local Device Bridge server is not reachable.

On the LeeWay Device Bridge app:
  1. ENABLE LOCAL AGENT SESSION
  2. START LOCAL DEVICE BRIDGE
  3. ENABLE ALWAYS-ON REMOTE BRIDGE

Then return to Termux and run this command again.
TXT
  exit 10
fi

printf '%s\n' "$LOCAL_HEALTH" > "$EVIDENCE_DIR/local-health.json"
node - "$EVIDENCE_DIR/local-health.json" <<'NODE'
const fs=require('fs');
const p=process.argv[2];
const v=JSON.parse(fs.readFileSync(p,'utf8'));
if(v.ok!==true||v.running!==true) throw new Error('LOCAL_BRIDGE_NOT_RUNNING');
if(v.agentAccessEnabled!==true) throw new Error('LOCAL_AGENT_ACCESS_DISABLED');
console.log('[LeeWay][PASS] Local bridge running:',v.bindAddress+':'+v.port);
console.log('[LeeWay][PASS] Agent access enabled:',v.agentAccessEnabled);
console.log('[LeeWay][PASS] Authority:',v.authority);
NODE

say "GATE 2 — staging the canonical remote controller pinned to ${PINNED_SHA}."
curl -fsSL "${BASE_RAW}/clients/remote-controller/client.mjs" -o "$WORK_ROOT/client.mjs"
curl -fsSL "${BASE_RAW}/clients/remote-controller/package.json" -o "$WORK_ROOT/package.json"
(
  cd "$WORK_ROOT"
  npm install --ignore-scripts --no-audit --no-fund >/dev/null
)

if [ -z "${LEEWAY_PAIRING_TOKEN:-}" ]; then
  printf '\nPaste the Device Bridge owner pairing token now. It stays only in this Termux process.\n'
  read -r -s -p "Pairing token: " LEEWAY_PAIRING_TOKEN
  printf '\n'
  export LEEWAY_PAIRING_TOKEN
fi
[ "${#LEEWAY_PAIRING_TOKEN}" -ge 20 ] || fail "Pairing token is too short."

export LEEWAY_DEVICE_ID="$DEVICE_ID"
export LEEWAY_RELAY_URL="$RELAY_URL"

run_cap(){
  local name="$1"; shift
  local cap="$1"; shift
  local args="$1"; shift || true
  say "Running ${cap}..."
  (
    cd "$WORK_ROOT"
    node client.mjs "$cap" "$args"
  ) | tee "$EVIDENCE_DIR/${name}.json"
}

run_cap "device-health" "device.health" '{}'
run_cap "model-status" "model.status" '{}'
run_cap "voice-status" "voice.status" '{}'
run_cap "model-inference" "model.inference" '{"prompt":"Respond with exactly: LEEWAY_PHONE_MODEL_READY"}'
run_cap "voice-speak" "voice.speak" '{"text":"Agent Lee phone voice execution path is verified."}'
run_cap "agent-chat" "agent.chat" '{"prompt":"Respond briefly: confirm this response was generated by the phone-local model, then say Direct phone path verified.","speak":true}'
run_cap "receipts" "device.receipts" '{}'

say "GATE 3 — validating remote result envelopes and generating a local receipt candidate."
node - "$EVIDENCE_DIR" <<'NODE'
const fs=require('fs'),path=require('path');
const dir=process.argv[2];
const files=['device-health','model-status','voice-status','model-inference','voice-speak','agent-chat','receipts'];
const summary={
  schema:'leeway-termux-direct-phone-qualification-v1',
  testedAt:new Date().toISOString(),
  results:{},
  humanAcousticConfirmation:'PENDING'
};
for(const name of files){
  const p=path.join(dir,name+'.json');
  const outer=JSON.parse(fs.readFileSync(p,'utf8'));
  if(outer.type!=='result') throw new Error(name+': NOT_RESULT_ENVELOPE');
  if(outer.ok!==true) throw new Error(name+': RELAY_FAIL '+(outer.error||'UNKNOWN'));
  const inner=outer.result;
  if(!inner||inner.ok!==true) throw new Error(name+': PHONE_FAIL '+(inner?.error||'UNKNOWN'));
  summary.results[name]={relay:'PASS',phone:'PASS',capability:inner.capability||null};
}
const health=JSON.parse(fs.readFileSync(path.join(dir,'device-health.json'),'utf8')).result?.result;
const model=JSON.parse(fs.readFileSync(path.join(dir,'model-status.json'),'utf8')).result?.result;
const voice=JSON.parse(fs.readFileSync(path.join(dir,'voice-status.json'),'utf8')).result?.result;
summary.observed={
  phoneAuthority:health?.authority||null,
  modelId:model?.modelId||null,
  modelVerified:Boolean(model?.verified),
  modelRuntime:model?.runtime||null,
  voiceEngine:voice?.engine||null,
  voiceReady:Boolean(voice?.ready)
};
fs.writeFileSync(path.join(dir,'qualification-summary.json'),JSON.stringify(summary,null,2));
console.log('\n[LeeWay][PASS] Remote controller authenticated.');
console.log('[LeeWay][PASS] Device Bridge commands executed on the phone.');
console.log('[LeeWay][PASS] Model/voice/agent.chat result envelopes passed.');
console.log('[LeeWay][INFO] Model:',summary.observed.modelId,'verified=',summary.observed.modelVerified);
console.log('[LeeWay][INFO] Voice engine:',summary.observed.voiceEngine,'ready=',summary.observed.voiceReady);
console.log('[LeeWay][INFO] Evidence:',path.join(dir,'qualification-summary.json'));
NODE

unset LEEWAY_PAIRING_TOKEN

printf '\n============================================================\n'
printf 'LEEWAY TERMUX DIRECT-PHONE QUALIFICATION: EXECUTED\n'
printf 'Evidence directory: %s\n' "$EVIDENCE_DIR"
printf '============================================================\n'
printf 'Human check: Did you hear BOTH spoken tests clearly?\n'
printf '  1. "Agent Lee phone voice execution path is verified."\n'
printf '  2. Agent Lee response ending with "Direct phone path verified."\n'
printf '\nSend me the terminal output from "[LeeWay][PASS] Remote controller authenticated." onward.\n'
printf 'Do NOT send the pairing token.\n'
